# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true    

    Respinar\ContaoSimplefaqBundle\:
        resource: ../src
        exclude: ../src/ContaoManager